// D3Q19 ordering and shifted distributions for the robot water pool.
// Like WebLBM, common WGSL is composed with small compute entry modules.
const S: u32 = 1u;
const F: u32 = 8u;
const I: u32 = 16u;
const G: u32 = 32u;
const IF: u32 = 24u;
const IG: u32 = 48u;
const GI: u32 = 56u;
// Transient newly uncovered particle cell; never interpreted as atmospheric gas.
const UNCOVERED: u32 = 64u;
override optimizedKernels:bool=false;
const C = array<vec3<i32>, 27>(
 vec3(0,0,0), vec3(1,0,0),vec3(-1,0,0), vec3(0,1,0),vec3(0,-1,0), vec3(0,0,1),vec3(0,0,-1),
 vec3(1,1,0),vec3(-1,-1,0), vec3(1,0,1),vec3(-1,0,-1), vec3(0,1,1),vec3(0,-1,-1),
 vec3(1,-1,0),vec3(-1,1,0), vec3(1,0,-1),vec3(-1,0,1), vec3(0,1,-1),vec3(0,-1,1),
 vec3(1,1,1),vec3(-1,-1,-1), vec3(1,1,-1),vec3(-1,-1,1), vec3(1,-1,1),vec3(-1,1,-1),vec3(-1,1,1),vec3(1,-1,-1));
struct Params {
 grid: vec4<u32>, // nx,ny,nz,N
 physical: vec4<f32>, // nu,sigma,gravity_z,scale
 geometry: vec4<f32>, // particleRadius,thetaP radians,thetaS radians,Smagorinsky Cs (0 disables LES)
 particleMin: vec4<f32>,
 particleMax: vec4<f32>,
 control: vec4<u32>, // lattice step,particle count,slice y,reserved
}
struct Cell {
 // excess is TOTAL pending mass, never a per-neighbour share. nextOwner is
 // reused for the recipient count only after the particle-map repair ends.
 rho:f32, mass:f32, phi:f32, excess:f32,
 ux:f32, uy:f32, uz:f32, flag:u32,
 owner:u32, nextOwner:u32, debt:f32, eddyViscosity:f32,
}
struct Particle { position:vec4<f32>, velocity:vec4<f32>, omega:vec4<f32>, /* BODY_AXIS */ }
@group(0) @binding(0) var<uniform> p:Params;
@group(0) @binding(1) var<storage,read_write> cells:array<Cell>;
@group(0) @binding(2) var<storage,read_write> flags:array<u32>;
@group(0) @binding(3) var<storage,read> particles:array<Particle>;
@group(0) @binding(5) var<storage,read_write> output:array<vec4<f32>>;
// Population bindings and popGet/popSet are generated by gpu.ts, bounded by
// maxStorageBufferBindingSize. FP16S compresses storage; arithmetic remains FP32.

fn coord(n:u32)->vec3<i32> { return vec3<i32>(i32(n%p.grid.x),i32(n/p.grid.x%p.grid.y),i32(n/(p.grid.x*p.grid.y))); }
fn periodicCoordinate(value:i32,size:i32)->i32 {
 let remainder=value%size;
 return select(remainder,remainder+size,remainder<0);
}
fn index(q:vec3<i32>)->u32 {
 let dims=vec3<i32>(p.grid.xyz);
 // The four lateral faces are periodic. The floor and ceiling are solid,
 // so clamping z only provides a safe lookup behind bounce-back nodes.
 let a=vec3(periodicCoordinate(q.x,dims.x),periodicCoordinate(q.y,dims.y),clamp(q.z,0,dims.z-1));
 return u32(a.x+(a.y+a.z*dims.y)*dims.x);
}
fn neighbor(n:u32,d:u32)->u32 { return index(coord(n)+C[d]); }
fn weight(d:u32)->f32 { if(d==0u){return 1.0/3.0;} if(d<7u){return 1.0/18.0;} return 1.0/36.0; }
fn opposite(d:u32)->u32 { if(d==0u){return 0u;} return select(d-1u,d+1u,(d&1u)==1u); }
fn velocity(n:u32)->vec3<f32>{return vec3(cells[n].ux,cells[n].uy,cells[n].uz);}
fn setVelocity(n:u32,u:vec3<f32>){cells[n].ux=u.x;cells[n].uy=u.y;cells[n].uz=u.z;}
fn wet(flag:u32)->bool{return flag==F||flag==I||flag==IF||flag==GI;}
fn safeNormal(v:vec3<f32>)->vec3<f32>{let l=length(v);return v/max(l,1e-12);}
fn wallVelocity(n:u32,owner:u32)->vec3<f32>{
 if(owner==0u){return vec3(0.0);} let a=particles[owner-1u];
 return a.velocity.xyz+cross(a.omega.xyz,vec3<f32>(coord(n))-a.position.xyz);
}
fn terrain(q:vec3<i32>)->bool{
 return q.z<=0||q.z>=i32(p.grid.z)-1;
}
fn initialFill(q:vec3<i32>)->bool{
 return f32(q.z)<=POOL_LEVEL*p.physical.w;
}
fn initialDensity(q:vec3<i32>)->f32{
 // cs^2=1/3 and the solver's constant force density give d(rho)/dz=3*g.
 let surface=floor(POOL_LEVEL*p.physical.w)+1.0;
 return 1.0+3.0*p.physical.z*min(0.0,f32(q.z)-surface);
}
fn covering(n:u32)->u32 {
 let q=vec3<f32>(coord(n));
 if(any(q<p.particleMin.xyz)||any(q>p.particleMax.xyz)){return 0u;}
 var owner=0u;
 for(var a=0u;a<p.control.y;a++){
  let body=particles[a];var r=q-body.position.xyz;
  /* BODY_DISTANCE */
  if(dot(r,r)<=particles[a].position.w*particles[a].position.w){owner=a+1u;}
 } return owner;
}
fn equilibrium(d:u32,rho:f32,u:vec3<f32>)->f32{
 let cu=3.0*dot(vec3<f32>(C[d]),u);
 return weight(d)*((rho-1.0)+rho*(cu+0.5*cu*cu-1.5*dot(u,u)));
}
fn incoming(n:u32,d:u32,t:u32)->f32{
 if(d==0u){return popGet(n,0u);}
 if((d&1u)==1u){return popGet(n,select(d+1u,d,(t&1u)==1u));}
 return popGet(neighbor(n,d-1u),select(d-1u,d,(t&1u)==1u));
}
fn outgoing(n:u32,d:u32,t:u32)->f32{
 if(d==0u){return popGet(n,0u);}
 if((d&1u)==1u){return popGet(neighbor(n,d),select(d+1u,d,(t&1u)==1u));}
 return popGet(n,select(d-1u,d,(t&1u)==1u));
}
fn storeF(n:u32,d:u32,t:u32,value:f32){
 // Store outgoing data for streaming/mass accounting and populate the
 // reflected slot for this map. Collision also reflects CURRENT solid links,
 // since the moving map can change before the next collision consumes them.
 if(d==0u){popSet(n,0u,value);return;}
 if((d&1u)==1u){popSet(neighbor(n,d),select(d,d+1u,(t&1u)==1u),value);}
 else{popSet(n,select(d,d-1u,(t&1u)==1u),value);}
 // The additional slot is owned by a non-colliding solid, so has no other
 // writer. Keep incoming diagnostics consistent with a completed bounce-back.
 if(flags[neighbor(n,d)]==S){reconstruct(n,opposite(d),t^1u,value);}
}
fn reconstruct(n:u32,d:u32,t:u32,value:f32){
 if((d&1u)==1u){popSet(n,select(d+1u,d,(t&1u)==1u),value);}
 else{popSet(neighbor(n,d-1u),select(d-1u,d,(t&1u)==1u),value);}
}
fn averageWet(n:u32)->vec4<f32>{
 var result=vec4(0.0);var count=0.0;
 for(var d=1u;d<19u;d++){let j=neighbor(n,d);if(wet(flags[j])){result+=vec4(velocity(j),cells[j].rho);count+=1.0;}}
 if(count==0.0){return vec4(0.0,0.0,0.0,1.0);}return result/count;
}
fn linearInvocation(id:vec3<u32>)->u32{return id.x+id.y*65535u*64u;}
